### ISSUE TITLE
Unable to scan channels

### ISSUE THREAD

**Issue by lassi-kojo** [fHDHR/fHDHR_plugin_origin_tvheadend#10]
Hi,

I have a fresh fHDHR install with tvheadend plugin running inside Docker container.

tvheadend is configured with user account, but I cannot find any channels and I see the following errors in the log:

```
fhdhr        | Starting fHDHR...
fhdhr        | [2021-06-02 21:38:20,330] NOOB - Loading fHDHR v0.9.0-beta with fHDHR_web v0.9.0-beta
fhdhr        | [2021-06-02 21:38:20,331] INFO - Importing Core config values from Configuration File: /config/config.ini
fhdhr        | [2021-06-02 21:38:20,331] DEBUG - Logging to File: /config/fHDHR/data/cache/logs/.fHDHR.log
fhdhr        | [2021-06-02 21:38:20,332] DEBUG - Scanning for Plugin Configuration files: /config/fHDHR/plugins
fhdhr        | [2021-06-02 21:38:20,332] INFO - Importing Plugin values from Configuration File: /config/config.ini
fhdhr        | [2021-06-02 21:38:20,333] INFO - Setting Up sqlite database
fhdhr        | [2021-06-02 21:38:20,341] DEBUG - Setting Up shared Web Requests system.
fhdhr        | [2021-06-02 21:38:20,346] DEBUG - Registering fHDHR item: fHDHR v0.9.0-beta
fhdhr        | [2021-06-02 21:38:20,346] DEBUG - Registering fHDHR item: fHDHR_web v0.9.0-beta
fhdhr        | [2021-06-02 21:38:20,347] DEBUG - Registering env item: Python 3.8.5 (default, Jan 27 2021, 15:41:15)
fhdhr        | [GCC 9.3.0]
fhdhr        | [2021-06-02 21:38:20,347] DEBUG - Registering env item: Operating System Linux
fhdhr        | [2021-06-02 21:38:20,348] WARNING - Do not run fHDHR with root privileges.
fhdhr        | [2021-06-02 21:38:20,348] DEBUG - Registering env item: Docker True
fhdhr        | [2021-06-02 21:38:20,349] DEBUG - Checking for Online Plugin Information
fhdhr        | [2021-06-02 21:38:26,766] INFO - Scanning for plugins: /config/fHDHR/plugins
fhdhr        | [2021-06-02 21:38:26,770] INFO - Found origin type plugin: Tvheadend v0.6.0-beta.
fhdhr        | [2021-06-02 21:38:26,771] INFO - Checking For Tvheadend Plugin Requirements file.
fhdhr        | [2021-06-02 21:38:26,773] INFO - Installing Tvheadend Plugin Requirements from /config/fHDHR/plugins/fHDHR_plugin_origin_tvheadend/requirements.txt
fhdhr        | [2021-06-02 21:38:26,776] INFO - Loading plugins.
fhdhr        | [2021-06-02 21:38:26,780] INFO - Scanning Plugins for Version Information.
fhdhr        | [2021-06-02 21:38:26,782] DEBUG - Registering plugin item: fHDHR_plugin_origin_tvheadend v0.6.0-beta
fhdhr        | [2021-06-02 21:38:26,784] INFO - Setting Up Plugin Pre-flight setups.
fhdhr        | [2021-06-02 21:38:26,786] INFO - Initializing fHDHR Core Functions.
fhdhr        | [2021-06-02 21:38:26,788] INFO - Detecting and Opening any found origin plugins.
fhdhr        | [2021-06-02 21:38:26,789] INFO - Found Origin: tvheadend
fhdhr        | [2021-06-02 21:38:26,790] INFO - tvheadend Origin Setup Success
fhdhr        | [2021-06-02 21:38:26,791] DEBUG - Giving Packaged non-origin Origin Plugins access to base origin plugin.
fhdhr        | [2021-06-02 21:38:26,793] DEBUG - Setting Up internal "Devices".
fhdhr        | [2021-06-02 21:38:26,793] INFO - Initializing Channels system
fhdhr        | [2021-06-02 21:38:26,794] INFO - Checking for tvheadend Channel information stored in the database.
fhdhr        | [2021-06-02 21:38:26,797] INFO - Initializing EPG system
fhdhr        | [2021-06-02 21:38:26,798] INFO - Detecting and Opening any found EPG plugins.
fhdhr        | [2021-06-02 21:38:26,799] DEBUG - Setting tvheadend update_frequency to default: 43200
fhdhr        | [2021-06-02 21:38:26,800] DEBUG - Setting tvheadend xmltv_offset to: +0000
fhdhr        | [2021-06-02 21:38:26,800] INFO - Initializing Tuners system
fhdhr        | [2021-06-02 21:38:26,801] INFO - Creating 4 tuners for tvheadend.
fhdhr        | [2021-06-02 21:38:26,802] INFO - Initializing Images system
fhdhr        | [2021-06-02 21:38:26,802] INFO - SSDP system will not be Initialized: Address not set in [ssdp]multicast_address or [fhdhr]discovery_address
fhdhr        | [2021-06-02 21:38:26,803] INFO - Detecting and Opening any found Interface plugins.
fhdhr        | [2021-06-02 21:38:26,804] INFO - Loading Flask.
fhdhr        | [2021-06-02 21:38:26,807] INFO - Loading HTTP brython Endpoints.
fhdhr        | [2021-06-02 21:38:26,809] DEBUG - Adding endpoint file_brython_js available at /brython.js with GET methods.
fhdhr        | [2021-06-02 21:38:26,810] DEBUG - Adding endpoint file_brython_bry available at /brython.bry with GET methods.
fhdhr        | [2021-06-02 21:38:26,811] DEBUG - Adding endpoint file_brython_stdlib_js available at /brython_stdlib.js with GET methods.
fhdhr        | [2021-06-02 21:38:26,812] INFO - Loading HTTP api Endpoints.
fhdhr        | [2021-06-02 21:38:26,813] DEBUG - Adding endpoint api_channels available at /api/channels with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,814] DEBUG - Adding endpoint api_debug available at /api/debug with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,815] DEBUG - Adding endpoint api_epg available at /api/epg with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,817] DEBUG - Adding endpoint api_images available at /api/images with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,818] DEBUG - Adding endpoint api_logs available at /api/logs with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,819] DEBUG - Adding endpoint api_m3u available at /api/m3u,/api/channels.m3u with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,820] DEBUG - Adding endpoint api_origins available at /api/origins with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,821] DEBUG - Adding endpoint api_plugins available at /api/plugins with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,822] DEBUG - Adding endpoint page_root_html available at / with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,823] DEBUG - Adding endpoint api_routes available at /api/routes with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,825] DEBUG - Adding endpoint api_settings available at /api/settings with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,826] DEBUG - Adding endpoint api_ssdp available at /api/ssdp with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,827] DEBUG - Adding endpoint api_startup_tasks available at /api/startup_tasks with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,828] DEBUG - Adding endpoint api_tuners available at /api/tuners with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,829] DEBUG - Adding endpoint api_versions available at /api/versions with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,830] DEBUG - Adding endpoint api_w3u available at /api/w3u with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,832] DEBUG - Adding endpoint api_xmltv available at /api/xmltv,/xmltv.xml with GET,POST methods.
fhdhr        | [2021-06-02 21:38:26,833] INFO - Loading HTTP tvheadend Endpoints.
fhdhr        | [2021-06-02 21:38:26,834] DEBUG - Adding endpoint page_tvh_html available at /tvh,/tvh.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,835] INFO - Loading HTTP pages Endpoints.
fhdhr        | [2021-06-02 21:38:26,836] DEBUG - Adding endpoint page_channel_delete_html available at /channel_delete,/channel_delete.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,838] DEBUG - Adding endpoint page_channels_editor_html available at /channels_editor,/channels_editor.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,839] DEBUG - Adding endpoint page_channels_html available at /channels,/channels.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,841] DEBUG - Adding endpoint page_diagnostics_html available at /diagnostics,/diagnostics.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,843] DEBUG - Adding endpoint page_guide_html available at /guide,/guide.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,844] DEBUG - Adding endpoint page_index_html available at /index,/index.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,846] DEBUG - Adding endpoint page_playlists_html available at /playlists,/playlists.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,847] DEBUG - Adding endpoint page_settings_html available at /settings,/settings.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,849] DEBUG - Adding endpoint page_ssdp_html available at /ssdp,/ssdp.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,850] DEBUG - Adding endpoint page_streams_html available at /tuners,/tuners.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,852] DEBUG - Adding endpoint page_versions_html available at /versions,/versions.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,854] DEBUG - Adding endpoint page_xmltv_html available at /xmltv,/xmltv.html with GET methods.
fhdhr        | [2021-06-02 21:38:26,854] INFO - Loading HTTP files Endpoints.
fhdhr        | [2021-06-02 21:38:26,855] DEBUG - Adding endpoint file_favicon_ico available at /favicon.ico with GET methods.
fhdhr        | [2021-06-02 21:38:26,856] DEBUG - Adding endpoint file_style_css available at /style.css with GET methods.
fhdhr        | [2021-06-02 21:38:26,857] INFO - Flask HTTP Thread Starting
fhdhr        | [2021-06-02 21:38:26,858] INFO - HTTP Server Online.
fhdhr        | [2021-06-02 21:38:26,859] DEBUG - Client is using internal API call.
fhdhr        | [2021-06-02 21:38:26,859] DEBUG - Client GET requested /api/startup_tasks Opening
fhdhr        | [2021-06-02 21:38:26,860] NOOB - Running Startup Tasks.
fhdhr        | [2021-06-02 21:38:26,862] DEBUG - Client is using internal API call.
fhdhr        | [2021-06-02 21:38:26,863] DEBUG - Client GET requested /api/channels Opening
fhdhr        | [2021-06-02 21:38:26,863] INFO - Checking for tvheadend Channel information stored in the database.
fhdhr        | [2021-06-02 21:38:26,865] INFO - Performing Channel Scan for tvheadend.
fhdhr        | [2021-06-02 21:38:26,867] ERROR - Channel Gathering Failed: Expecting value: line 1 column 1 (char 0)
fhdhr        | [2021-06-02 21:38:26,868] INFO - Found 0 channels for tvheadend.
fhdhr        | [2021-06-02 21:38:26,868] INFO - Performing tvheadend Channel Import, This can take some time, Please wait.
fhdhr        | [2021-06-02 21:38:26,869] INFO - tvheadend Channel Import took just now
fhdhr        | [2021-06-02 21:38:26,869] INFO - Found no NEW channels for tvheadend.
fhdhr        | [2021-06-02 21:38:26,870] INFO - Total tvheadend Channel Count: 0
fhdhr        | [2021-06-02 21:38:26,870] DEBUG - Saving tvheadend channels to database.
fhdhr        | [2021-06-02 21:38:26,895] DEBUG - Client GET requested /api/channels Closing
fhdhr        | [2021-06-02 21:38:26,900] DEBUG - Client is using internal API call.
fhdhr        | [2021-06-02 21:38:26,900] DEBUG - Client GET requested /api/epg Opening
fhdhr        | [2021-06-02 21:38:26,901] NOOB - Updating tvheadend EPG cache.
fhdhr        | Checking and Installing Core Dependencies.
fhdhr        | Traceback (most recent call last):
fhdhr        |   File "/config/fHDHR/main.py", line 30, in <module>
fhdhr        |     sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
fhdhr        |   File "/config/fHDHR/fHDHR/cli/run.py", line 147, in main
fhdhr        |     returned_code = start(args, script_dir, fHDHR_web, deps)
fhdhr        |   File "/config/fHDHR/fHDHR/cli/run.py", line 120, in start
fhdhr        |     return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
fhdhr        |   File "/config/fHDHR/fHDHR/cli/run.py", line 49, in run
fhdhr        |     fhdhr.api.get("/api/startup_tasks")
fhdhr        |   File "/config/fHDHR/fHDHR/api/__init__.py", line 104, in get
fhdhr        |     self.client.get(url, headers=self.headers, *args)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1006, in get
fhdhr        |     return self.open(*args, **kw)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 222, in open
fhdhr        |     return Client.open(
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 970, in open
fhdhr        |     response = self.run_wsgi_app(environ.copy(), buffered=buffered)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 861, in run_wsgi_app
fhdhr        |     rv = run_wsgi_app(self.application, environ, buffered=buffered)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1096, in run_wsgi_app
fhdhr        |     app_rv = app(environ, start_response)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
fhdhr        |     return self.wsgi_app(environ, start_response)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
fhdhr        |     response = self.handle_exception(e)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
fhdhr        |     reraise(exc_type, exc_value, tb)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
fhdhr        |     raise value
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
fhdhr        |     response = self.full_dispatch_request()
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
fhdhr        |     rv = self.handle_user_exception(e)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
fhdhr        |     reraise(exc_type, exc_value, tb)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
fhdhr        |     raise value
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
fhdhr        |     rv = self.dispatch_request()
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
fhdhr        |     return self.view_functions[rule.endpoint](**req.view_args)
fhdhr        |   File "/config/fHDHR/fHDHR_web/api/startup_tasks.py", line 15, in __call__
fhdhr        |     return self.get(*args)
fhdhr        |   File "/config/fHDHR/fHDHR_web/api/startup_tasks.py", line 36, in get
fhdhr        |     self.fhdhr.api.get("%s&source=%s" % (self.epg_update_url, epg_method))
fhdhr        |   File "/config/fHDHR/fHDHR/api/__init__.py", line 104, in get
fhdhr        |     self.client.get(url, headers=self.headers, *args)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1006, in get
fhdhr        |     return self.open(*args, **kw)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/testing.py", line 222, in open
fhdhr        |     return Client.open(
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 970, in open
fhdhr        |     response = self.run_wsgi_app(environ.copy(), buffered=buffered)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 861, in run_wsgi_app
fhdhr        |     rv = run_wsgi_app(self.application, environ, buffered=buffered)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/werkzeug/test.py", line 1096, in run_wsgi_app
fhdhr        |     app_rv = app(environ, start_response)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__
fhdhr        |     return self.wsgi_app(environ, start_response)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
fhdhr        |     response = self.handle_exception(e)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
fhdhr        |     reraise(exc_type, exc_value, tb)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
fhdhr        |     raise value
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
fhdhr        |     response = self.full_dispatch_request()
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
fhdhr        |     rv = self.handle_user_exception(e)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
fhdhr        |     reraise(exc_type, exc_value, tb)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
fhdhr        |     raise value
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
fhdhr        |     rv = self.dispatch_request()
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
fhdhr        |     return self.view_functions[rule.endpoint](**req.view_args)
fhdhr        |   File "/config/fHDHR/fHDHR_web/api/epg.py", line 19, in __call__
fhdhr        |     return self.get(*args)
fhdhr        |   File "/config/fHDHR/fHDHR_web/api/epg.py", line 100, in get
fhdhr        |     self.fhdhr.device.epg.update(source)
fhdhr        |   File "/config/fHDHR/fHDHR/device/epg/__init__.py", line 424, in update
fhdhr        |     programguide = self.epg_handling[method]["class"].update_epg()
fhdhr        |   File "/config/fHDHR/plugins/fHDHR_plugin_origin_tvheadend/epg/__init__.py", line 34, in update_epg
fhdhr        |     entries = r.json()['entries']
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
fhdhr        |     return complexjson.loads(self.text, **kwargs)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/simplejson/__init__.py", line 525, in loads
fhdhr        |     return _default_decoder.decode(s)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 370, in decode
fhdhr        |     obj, end = self.raw_decode(s)
fhdhr        |   File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 400, in raw_decode
fhdhr        |     return self.scan_once(s, idx=_w(s, idx).end())
fhdhr        | simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

And the following error comes up if I try to manually force scan channels:

```
fhdhr        | [2021-06-02 21:54:09,428] DEBUG - Client GET requested /api/tuners Opening
fhdhr        | [2021-06-02 21:54:09,429] INFO - Tuner #0 Acquired.
fhdhr        | [2021-06-02 21:54:09,430] INFO - Tuner #0 Performing Channel Scan for tvheadend origin.
fhdhr        | [2021-06-02 21:54:09,431] DEBUG - Client is using internal API call.
fhdhr        | [2021-06-02 21:54:09,432] DEBUG - Client GET requested /api/channels Opening
fhdhr        | [2021-06-02 21:54:09,433] INFO - Checking for tvheadend Channel information stored in the database.
fhdhr        | [2021-06-02 21:54:09,435] INFO - Performing Channel Scan for tvheadend.
fhdhr        | [2021-06-02 21:54:09,436] DEBUG - Client GET requested /api/tuners Closing
fhdhr        | [2021-06-02 21:54:09,440] INFO - 192.168.100.94 - - [2021-06-02 21:54:09] "GET /api/tuners?method=scan&origin=tvheadend&redirect=/channels?origin=tvheadend HTTP/1.1" 302 2241 0.012892
fhdhr        | [2021-06-02 21:54:09,442] ERROR - Channel Gathering Failed: Expecting value: line 1 column 1 (char 0)
fhdhr        | [2021-06-02 21:54:09,443] INFO - Found 0 channels for tvheadend.
fhdhr        | [2021-06-02 21:54:09,444] INFO - Performing tvheadend Channel Import, This can take some time, Please wait.
fhdhr        | [2021-06-02 21:54:09,444] INFO - tvheadend Channel Import took just now
fhdhr        | [2021-06-02 21:54:09,445] INFO - Found no NEW channels for tvheadend.
fhdhr        | [2021-06-02 21:54:09,445] INFO - Total tvheadend Channel Count: 0
fhdhr        | [2021-06-02 21:54:09,446] DEBUG - Saving tvheadend channels to database.
fhdhr        | [2021-06-02 21:54:09,463] DEBUG - Client GET requested /api/channels Closing
fhdhr        | [2021-06-02 21:54:09,467] INFO - Requested Channel Scan for tvheadend origin Complete.
fhdhr        | [2021-06-02 21:54:09,467] INFO - Tuner #0 Released.
fhdhr        | [2021-06-02 21:54:09,468] DEBUG - Starting a thread to simulate a GET request to /api/tuners?method=close&tuner=0&origin=tvheadend
fhdhr        | [2021-06-02 21:54:09,469] DEBUG - Client is using internal API call.
fhdhr        | [2021-06-02 21:54:09,470] DEBUG - Client GET requested /api/tuners Opening
fhdhr        | [2021-06-02 21:54:09,471] DEBUG - Client GET requested /api/tuners Closing
fhdhr        | [2021-06-02 21:54:09,483] DEBUG - Client GET requested /channels Opening
fhdhr        | [2021-06-02 21:54:09,484] INFO - Checking for tvheadend Channel information stored in the database.
fhdhr        | [2021-06-02 21:54:09,485] INFO - Checking for tvheadend Channel information stored in the database.
fhdhr        | [2021-06-02 21:54:09,487] DEBUG - Client GET requested /channels Closing
fhdhr        | [2021-06-02 21:54:09,490] INFO - 192.168.100.94 - - [2021-06-02 21:54:09] "GET /channels?origin=tvheadend&retmessage=scan%20Success HTTP/1.1" 200 5671 0.008147
fhdhr        | [2021-06-02 21:54:09,592] DEBUG - Client GET requested /brython.js Opening
fhdhr        | [2021-06-02 21:54:09,593] DEBUG - Client GET requested /brython.js Closing
fhdhr        | [2021-06-02 21:54:09,596] INFO - 192.168.100.94 - - [2021-06-02 21:54:09] "GET /brython.js HTTP/1.1" 304 1899 0.005258
fhdhr        | [2021-06-02 21:54:09,598] DEBUG - Client GET requested /brython_stdlib.js Opening
fhdhr        | [2021-06-02 21:54:09,599] DEBUG - Client GET requested /brython_stdlib.js Closing
fhdhr        | [2021-06-02 21:54:09,602] INFO - 192.168.100.94 - - [2021-06-02 21:54:09] "GET /brython_stdlib.js HTTP/1.1" 304 1903 0.005005
fhdhr        | [2021-06-02 21:54:09,907] DEBUG - Client GET requested /style.css Opening
fhdhr        | [2021-06-02 21:54:09,908] DEBUG - Client GET requested /style.css Closing
fhdhr        | [2021-06-02 21:54:09,912] INFO - 192.168.100.94 - - [2021-06-02 21:54:09] "GET /style.css HTTP/1.1" 200 4772 0.005454
fhdhr        | [2021-06-02 21:54:10,140] DEBUG - Client GET requested /favicon.ico Opening
fhdhr        | [2021-06-02 21:54:10,142] DEBUG - Client GET requested /favicon.ico Closing
fhdhr        | [2021-06-02 21:54:10,145] INFO - 192.168.100.94 - - [2021-06-02 21:54:10] "GET /favicon.ico HTTP/1.1" 200 17406 0.005785
fhdhr        | [2021-06-02 21:54:10,172] DEBUG - Client GET requested /brython.bry Opening
fhdhr        | [2021-06-02 21:54:10,173] DEBUG - Client GET requested /brython.bry Closing
fhdhr        | [2021-06-02 21:54:10,176] INFO - 192.168.100.94 - - [2021-06-02 21:54:10] "GET /brython.bry?1622660050049 HTTP/1.1" 200 8016 0.005223
```

I have tried the official Docker image and 3rd party one (which pulls the latest version from git), same results with both.

Thank you!

**Comment by deathbybandaid** [comment]
How many channels do you have in tvheadend?

**Comment by deathbybandaid** [comment]
I can add some error handling for the epg grabbing error tomorrow though.

**Comment by lassi-kojo** [comment]
Thank you for taking a look at this!

I have 21 channels in tvheadend.

**Comment by deathbybandaid** [comment]
Pushed a patch to cleanly handle the EPG update error. #11 

However, that doesn't fix the channel gathering issue.  In a browser, I'll have you look at the tvheadend api that it tries to gather from. Let me know what you see at (make sure you use the credentials you supplied to fHDHR):

`http://<ip>:<port>/api/channel/grid?start=0&limit=999999`

Normally, this looks like:


`
{"entries":[{"uuid":"dcc56a868793c1cb74dece387f9684f4","enabled":true,"autoname":true,"name":"WLUCGRT","number":"6.3","icon":"https://zap2it.tmsimg.com/h3/NowShowing/49214/s89922_h3_aa.png","icon_public_url":"imagecache/997","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["ad5080ec821507e5aad788c362576c0e"],"tags":[],"bouquet":""},{"uuid":"45466b065c9dee782a81127bf06e13db","enabled":true,"autoname":true,"name":"WLUCNBC","number":"6.1","icon":"https://zap2it.tmsimg.com/h3/NowShowing/42644/s28717_h3_aa.png","icon_public_url":"imagecache/999","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["1c3fe03df31da5cb99b4650c15d3a556"],"tags":[],"bouquet":""},{"uuid":"94ca430bac8850691d023a104362d90c","enabled":true,"autoname":true,"name":"Bounce","number":"3.4","icon":"https://zap2it.tmsimg.com/h3/NowShowing/100748/s73067_h3_aa.png","icon_public_url":"imagecache/1000","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["edbf5bf5a55f76fd9b079ba8b14890eb"],"tags":[],"bouquet":""},{"uuid":"e335fd8dfb32e82e08a7092523ed8a70","enabled":true,"autoname":true,"name":"WLUCFOX","number":"6.2","icon":"https://zap2it.tmsimg.com/h3/NowShowing/49212/s28719_h3_aa.png","icon_public_url":"imagecache/995","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["17dc19f8419423e15101dfd270ec8cc5"],"tags":[],"bouquet":""},{"uuid":"135859ae0218a33906ba6b0bd43b9e06","enabled":true,"autoname":true,"name":"Escape","number":"3.2","icon":"https://zap2it.tmsimg.com/h3/NowShowing/100744/s89923_h3_aa.png","icon_public_url":"imagecache/996","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["26db058c236c0a338334c60ee09ab3b4"],"tags":[],"bouquet":""},{"uuid":"b4ea934821fec48a285da2adaee2d4e2","enabled":true,"autoname":true,"name":"Laff","number":"3.3","icon":"https://zap2it.tmsimg.com/h3/NowShowing/100745/s92091_h3_aa.png","icon_public_url":"imagecache/1001","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["1762d43012dff74e136668844356e71a"],"tags":[],"bouquet":""},{"uuid":"92b3bbed39198eb0b3c66bee857d6672","enabled":true,"autoname":true,"name":"WJMN-HD","number":"3.1","icon":"https://zap2it.tmsimg.com/h3/NowShowing/49381/s28711_h3_aa.png","icon_public_url":"imagecache/998","epgauto":true,"epggrab":[],"dvr_pre_time":0,"dvr_pst_time":0,"epg_running":1,"services":["6e745dae0066b7067acf6f9813cf3f66"],"tags":[],"bouquet":""}],"total":7}
`

**Comment by lassi-kojo** [comment]
> However, that doesn't fix the channel gathering issue. In a browser, I'll have you look at the tvheadend api that it tries to gather from. Let me know what you see at (make sure you use the credentials you supplied to fHDHR):
> 
> http://<ip>:<port>/api/channel/grid?start=0&limit=999999

I get my channels back, total 21, valid JSON structure and everything looks good.

**Comment by deathbybandaid** [comment]
Are you able to try fHDHR without docker, just to eliminate that as an issue? I'm not a docker kinda guy, but it should work fine in a container.

**Comment by lassi-kojo** [comment]
Sure, I'll check back later!

**Comment by lassi-kojo** [comment]
> 
> 
> Are you able to try fHDHR without docker, just to eliminate that as an issue? I'm not a docker kinda guy, but it should work fine in a container.

I don't think that the issue lies with Docker setup, I entered the container the ran the Python interpreter:
`docker-compose exec fhdhr python3`

Imported requests and tried to query the API:
```
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('http://tvheadend:9981/api/channel/grid?start=0&limit=999999', auth=('USERNAME', 'PASSWORD')
<Response [401]>
```

Guessed incorrectly that tvheadend API would use HTTP Basic Auth, let's try with Digest:
```
>>> from requests.auth import HTTPDigestAuth
>>> test = requests.get('http://tvheadend:9981/api/channel/grid?start=0&limit=999999', auth=HTTPDigestAuth('USERNAME', 'PASSWORD'))
>>> print (test)
<Response [200]>
>>> print (test.content)
b'{"entries":[{"uuid":"ee89ee040ad83a6c600d83sasd1d0","enabled":true,"autoname":..... CLIP
21 channels.
```

Success.
So I am able to query tvheadend from the fHDHR docker container.
If you want, I can still try it without Docker.

**Comment by deathbybandaid** [comment]
that looks like it should work. *scratches head*

I just know that I've been using my setup for a long time, and haven't had issue.

Mind giving me your tvheadend version?

**Comment by deathbybandaid** [comment]
I confirm mine works on 4.2.8-36~g5bdcfd8ac

**Comment by lassi-kojo** [comment]
Sure, I have 4.3-1965~g9476680f8

**Comment by deathbybandaid** [comment]
Wondering if they changed something in their API between versions 4.2 and 4.3

**Comment by deathbybandaid** [comment]
Looks like 4.3 is a pre-release?

**Comment by deathbybandaid** [comment]
Really confused, because the newest tag is 4.2.8??

https://github.com/tvheadend/tvheadend/releases

**Comment by deathbybandaid** [comment]
"Development is the recommended choice for most people as Stable is very out-of-date at the moment."

That's counter-intuitive.

**Comment by deathbybandaid** [comment]
Updated my local instance, and now I'm locked out

**Comment by deathbybandaid** [comment]
looks like I'm going to have to reconfigure my entire tvheadend to troubleshoot your issue. Might take some time.

**Comment by lassi-kojo** [comment]
Sorry to hear that, I hope you had backups. Well, I guess if you do it now, you don’t have to do it later when you update :) silver lining etc.

**Comment by deathbybandaid** [comment]
I have mine setup in a lxc, with daily backups. I can always restore to 4.2.8,,, but I can't seem to get past 403 Forbidden with 4.3

**Comment by deathbybandaid** [comment]
I think I'll restore my backup and make a new container and do a fresh install

**Comment by deathbybandaid** [comment]
Things came up at work today, so I will return to this tomorrow. (apparently my employer doesn't pay me to work on fun projects!?)

**Comment by deathbybandaid** [comment]
okay, I managed to get 4.3 running, and indeed, something changed in the response from tvheadend. 4.2 works, 4.3 doesn't.

I'll work on trying to add some handling for supporting both versions

**Comment by lassi-kojo** [comment]
OK, I figured it out.

As I previously noticed, latest tvheadend doesn't support HTTP Basic Authentication OOTB. And that seems to be the way this plugin (or fHDHR) works. Basic auth can be enabled from tvheadend web ui: General -> Base -> (make sure view level is Expert) HTTP Server Settings -> Authentication Type -> Both plain and digest.
After that change, fHDHR finds the channels.

Maybe we could support both types?

**Comment by deathbybandaid** [comment]
that seems like a good enough workaround, until I have time to look at the digest auth
